### ISSUE TITLE
blockcount not functioning correctly

### ISSUE THREAD

**Issue by vizerei** [dodexahedron/EssentialsPlugin#2]
Using /admin scan grids blockcount:3000 returns 0 results although I have checked the block count on multiple grids and have verified that they are over 3000.

However, it seems to return almost every ship on the server if I do a blockcount:10.

**Comment by dodexahedron** [comment]
Interesting.
I've really not taken a look at any of the Essentials code.
I guess I'll have to check it out.
I assume you aren't seeing any exceptions?

**Comment by dodexahedron** [comment]
The logic for blockcount is somewhat spread out over the monolithic ScanGrids function.
Assuming you're only entering blockcount, with no other parameters other than the count (ie no types, not specifying functional, etc), then it should count all grids, of all sizes, which contain greater than or equal to that number of blocks.

In the latest commit of essentials, the line that determines if a grid is included by blockcount is line 1030 of EsssentialsPlugin/Utility/CubeGrids/CubeGrid.cs.
As you can see, so long as the game reports at least the entered number of blocks, found should not be set false, and thus the grid will be included.

I haven't scrutinized the rest of the code, though, so there could also potentially be an argument parser problem, or else the game just isn't properly reporting back the cube count.  Those really are the only two options, if you entered the command exactly as you showed here.

**Comment by vizerei** [comment]
SO..if I scan for grids with more than 1000 blocks, I get this:

7:58:32 PM - Server - /admin scan grids blockcount:1000
7:58:32 PM - Server - Scanning for ships with options: Requires Block Count=true, Block Count:=1000
7:58:33 PM - Server - Found grid 'Large Ship 4224' (173041945885404224) (Owner: Luftwaffle) which has specified parameters.  BlockCount=1087
7:58:33 PM - Server - Found grid 'Helix Station' (147667068868829739) (Owner: Killershark) which has specified parameters.  BlockCount=1373
7:58:33 PM - Server - Found grid 'Dread Hulk Nefarious [A2-9604-p]' (201734479608660520) (Owner: none) which has specified parameters.  BlockCount=1926
7:58:33 PM - Server - Found grid 'Small Ship 9377' (189258118838997600) (Owner: nmmichris) which has specified parameters.  BlockCount=1663
7:58:33 PM - Server - Found 4 grids
7:58:47 PM - Server - /admin scan grids blockcount:2000
7:58:47 PM - Server - Scanning for ships with options: Requires Block Count=true, Block Count:=2000
7:58:48 PM - Server - Found 0 grids


However, as you can see the scan doesn't list anything more than 2000 blocks, and the scan for over 2000 blocks returns nothing.  I currently own two grids with more than that (large ships with 3800 blocks and station with over 8000 blocks).  It seems that it does not consider anything more than 2000, as I see no grids over 2000; but, that number could be higher or lower as there very well may be no ship over 2000 and under 3000 (or some other arbitrary number).

**Comment by dodexahedron** [comment]
The code in Essentials doesn't cause that limitation.
Here are my results, on a world where this should return a lot more than what it did return:

3:47:58 AM - Server - /admin scan grids blockcount:2000
3:47:58 AM - Server - Scanning for ships with options: Requires Block Count=true, Block Count:=2000
3:47:58 AM - Server - Found grid 'The Absolute' (2822804867974106402) (Owner: Randomplayer) which has specified parameters.  BlockCount=5990

I should be seeing several more results there, including a station of over 60,000 blocks.

I think the fault lies with the function GetGridsUnconnected.
That's the source of the grids the function will ultimately process, so that function must be excluding some grids unexpectedly.

I'll have to analyze that function when it's not 4AM.

**Comment by dodexahedron** [comment]
Actually...
That wasn't as bad as I thought...

That function is almost definitely to blame, because it excludes the grid if any of the following conditions are met:

 * Has any component of a piston
 * Has a connector which is connected to another CubeGrid
 * Has a motor which is connected to another CubeGrid

I know  that would exclude the station I should be seeing.

I removed the call to that function, since I honestly couldn't come up with a purpose for it to be called there, and here's the new result:

4:09:53 AM - Server - /admin scan grids blockcount:5000
4:09:53 AM - Server - Scanning for ships with options: Requires Block Count=true, Block Count:=5000
4:09:53 AM - Server - Found grid 'Platform' (7613776772772992045) (Owner: Randomplayer) which has specified parameters.  BlockCount=70065
4:09:53 AM - Server - Found grid 'The Absolute' (2822804867974106402) (Owner: Randomplayer) which has specified parameters.  BlockCount=5990

**Comment by dodexahedron** [comment]
This is fixed.
Closing.

**Comment by vizerei** [comment]
You're absolutely right on that, pistons on everything.

Also, I literally thought you were in a different timezone, but now see that you are a hardcore night owl :P.  Get some sleep
